# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Meng
tagline:          'Michelle Nguyen's Portfolio'
description:      'My name is Michelle Nguyen but you can call me <a class="link" href="http://twitter.com/allthingsmeng" target="_blank">Meng</a>.<br /><br />I have a passion for design, illustration and animation. I love to draw comics, cartoons and random people on the bus.'
url:              http://michellemeng.com
baseurl:          /
host: 0.0.0.0

#Personal Info
author:
  name:           'Michelle Meng Nguyen'
  url:            https://twitter.com/allthingsmeng
blog: http://blog.michellemeng.com
email: me@michellemeng.com
resume: http://resume.michellemeng.com/
linkedin: http://www.linkedin.com/in/michellemengnguyen
dribbble: http://dribbble.com/allthingsmeng

paginate:         100
